# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://eystein.nordby.meese@pwc.com.github.io/mapaccounting/"

git_url = "https://github.com/eystein.nordby.meese@pwc.com/mapaccounting/tree/master/"

def custom_doc_links(name): return None
